### ISSUE TITLE
The package could not bet installed on FreeBSD

### ISSUE THREAD

**Issue by jszhao** [joshuaulrich/microbenchmark#49]
### Description

I tried to install `microbenchmark` in R 4.4.1 on a FreeBSD 14.1 machine. The CC compiler is GCC 13.2.0. I get the following error message. 
```
In file included from nanotimer.c:9:
nanotimer_clock_gettime.h: In function 'get_nanotime':
config.h:35:22: error: 'CLOCK_MONOTONIC_PRECISE' undeclared (first use in this function); did you mean 'CLOCK_MONOTONIC'?
   35 | #define MB_CLOCKID_T CLOCK_MONOTONIC_PRECISE
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
nanotimer_clock_gettime.h:13:19: note: in expansion of macro 'MB_CLOCKID_T'
   13 |     clock_gettime(MB_CLOCKID_T, &time_var);
      |                   ^~~~~~~~~~~~
config.h:35:22: note: each undeclared identifier is reported only once for each function it appears in
   35 | #define MB_CLOCKID_T CLOCK_MONOTONIC_PRECISE
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
nanotimer_clock_gettime.h:13:19: note: in expansion of macro 'MB_CLOCKID_T'
   13 |     clock_gettime(MB_CLOCKID_T, &time_var);
      |                   ^~~~~~~~~~~~
gmake: *** [/usr/local/lib/R/etc/Makeconf:195: nanotimer.o] Error 1
```

### Expected behavior

It should be installed into R 4.4.1.

### Minimal, reproducible example

```r
install.packages("microbenchmark")
```

### Session Info

```r
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: amd64-portbld-freebsd14.0
Running under: FreeBSD aoi 14.1-RELEASE-p3 FreeBSD 14.1-RELEASE-p3 GENERIC amd64

Matrix products: default
LAPACK: /usr/local/lib/R/lib/libRlapack.so;  LAPACK version 3.12.0

locale:
[1] C.UTF-8/C.UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8

time zone: NA
tzcode source: system (FreeBSD)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.4.1 tools_4.4.1
```

**Comment by jszhao** [comment]
I also tried to use the clang compiler on FreeBSD, the error message is as follows:
```
In file included from nanotimer.c:22:
./nanotimer_clock_gettime.h:13:19: error: use of undeclared identifier 'CLOCK_MONOTONIC_PRECISE'
   13 |     clock_gettime(MB_CLOCKID_T, &time_var);
      |                   ^
./config.h:35:22: note: expanded from macro 'MB_CLOCKID_T'
   35 | #define MB_CLOCKID_T CLOCK_MONOTONIC_PRECISE
      |                      ^
1 error generated.
gmake: *** [/usr/local/lib/R/etc/Makeconf:195: nanotimer.o] Error 1
```

**Comment by jszhao** [comment]
The issue is duplicated with #33, and it has been solved with pull request [#41](https://github.com/joshuaulrich/microbenchmark/pull/41).

**Comment by joshuaulrich** [comment]
Thanks for the report and the reminder to merge the fix!

**Comment by yimwy** [comment]
Hi, I received the same error during installation, any possible fix? Appreciate it!

![图片](https://github.com/user-attachments/assets/fe2ae0a9-7dd9-4fd9-8485-57c7a3bc2111)

**Comment by yimwy** [comment]
Hi Joshua, thanks for the quick response! I've tried installation with remotes::install_github, unfortunately I'm still getting the same error. Attached is the sessioninfo. 

![图片](https://github.com/user-attachments/assets/2ba0e2a1-d284-497e-bf39-f81d471e2b74)
![图片](https://github.com/user-attachments/assets/25d18b8c-1739-424c-b609-4c805d2fbaaf)

**Comment by yimwy** [comment]
Hi, I've tested the installation in another device which uses gcc9 instead of 12 and was successful. After downgrading removing gcc12, the installation became success, sorry for the trouble!

**Comment by joshuaulrich** [comment]
Thanks for following up. I doubt it's related to the compiler version. I'm using gcc 13 on Ubuntu and it compiles fine.

I think your issue is that you were using a conda-forge gcc compiler and that conda installation doesn't have a `clock_gettime()`. The configure script should throw an error at that point, but doesn't. That's a bug, so I'll update the configure script to throw an error like it should.

**Comment by joshuaulrich** [comment]
@jszhao this fix is on CRAN now
